sudo: false
language: node_js
node_js:
  - "6.1.0"
before_script:
  - npm install -g grunt-cli
  - npm install -g phantomjs
  - grunt test
script: phantomjs test/index.html
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"